apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    app: node-goof-mongo-github-dockerhub-gke
    io.kompose.service: goof-mongo
  name: node-goof-mongo-github-dockerhub-gke
  namespace: node-goof-github-dockerhub-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-goof-mongo-github-dockerhub-gke
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        app: node-goof-mongo-github-dockerhub-gke
        io.kompose.network/node-goof-github-dockerhub-gke-default: "true"
        io.kompose.service: node-goof-mongo-github-dockerhub-gke
    spec:
      containers:
        - env:
            - name: DOCKER
              value: "1"
          image: mongo:3
          name: node-goof-mongo-github-dockerhub-gke
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
