apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-goof-mongo-github-dockerhub-gke
  name: node-goof-mongo-github-dockerhub-gke
  namespace: node-goof-github-dockerhub-gke
spec:
  type: LoadBalancer
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: node-goof-mongo-github-dockerhub-gke
