apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-goof-github-dockerhub-gke
  name: node-goof-github-dockerhub-gke
  namespace: node-goof-github-dockerhub-gke
spec:
  type: LoadBalancer
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
    - name: "9229"
      port: 9229
      targetPort: 9229
  selector:
    app: node-goof-github-dockerhub-gke
