apiVersion: v1
kind: Service
metadata:
  labels:
    app: goof-mongo
  name: goof-mongo
  namespace: node-goof-github-dockerhub-gke
spec:
  type: LoadBalancer
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: goof-mongo
#status:
#  loadBalancer: {}
